basePath: /
info:
  contact: {}
  title: User API documentation
paths:
  /api/v1/auth/temp:
    get:
      consumes:
      - application/json
      description: check integrating swagger
      responses:
        "200":
          description: ""
      summary: check api
      tags:
      - Authentication
swagger: "2.0"
